name: Reddit to Discord webhook

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Download last run timestamp artifact
        uses: actions/download-artifact@v4
        with:
          name: last-run-timestamp
        continue-on-error: true  # In case artifact doesn't exist on first run

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install praw requests

      - name: Run Reddit to Discord script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python discordRSS.py

      - name: Upload updated timestamp
        uses: actions/upload-artifact@v4
        with:
          name: last-run-timestamp
          path: last_run.txt
